### ISSUE TITLE
Redirection BASH != 42

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#20]
42sh √ pwd > test > test2 > test3
42sh √ cat test3
42sh √
42sh √ cat test
/Users/gbourson/Documents/42sh
-------------------------------BASH VERSION---------------------------------
bash-3.2$ pwd > test > test2 > test3
bash-3.2$ cat test3
/Users/gbourson/Documents/app-test
bash-3.2$ cat test
bash-3.2$

**Comment by alexandre-roulin** [comment]
On le fais a la bien couzin
