### ISSUE TITLE
Function pour open a faire !

### ISSUE THREAD

**Issue by alexandre-roulin** [Krystalz42/42sh#22]
faire une fct qui open selon les possibilite

**Comment by alexandre-roulin** [comment]
Access etc

**Comment by alexandre-roulin** [comment]
C"est JEFFERSON QUI FERA CELLE LA

**Comment by jle-quel** [comment]
`int         create_fd(char *str, int option, int write, int chmod)`

**Comment by jle-quel** [comment]
int create_fd(char *str, int option, int chmod)

**Comment by alexandre-roulin** [comment]
`int create_fildes(char *str, int option, int chmod)`

**Comment by alexandre-roulin** [comment]
`int create_fildes(char *path, int option, int chmod)`
