### ISSUE TITLE
SEGFAULT

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#23]
echo "\$TOTO"

**Comment by razorbarbeuk** [comment]
J'ai unsetenv toutes les variables de l'env
ensuite echo "\$TOTO"

ASAN:DEADLYSIGNAL
=================================================================
==80521==ERROR: AddressSanitizer: SEGV on unknown address 0x0000632e6e72 (pc 0x0001015c529e bp 0x7fff5e63d4b0 sp 0x7fff5e63d4b0 T0)
==80521==The signal is caused by a READ memory access.
    #0 0x1015c529d in ft_strncmp (42sh:x86_64+0x10000329d)
    #1 0x1015d8570 in check_env ft_echo.c:30
    #2 0x1015d83ca in print_echo ft_echo.c:47
    #3 0x1015d82fe in ft_echo ft_echo.c:89
    #4 0x1015d340a in check_if_builtin check_if_builtins.c:45
    #5 0x1015d4762 in op_execution op_execution.c:48
    #6 0x1015d3480 in execute_node executing_node.c:20
    #7 0x1015cb684 in shell shell.c:45
    #8 0x1015cb453 in main main.c:23
    #9 0x7fffcf6d5234 in start (libdyld.dylib:x86_64+0x5234)

==80521==Register values:
rax = 0x0000000000000000  rbx = 0x0000000000000000  rcx = 0x0000000000000000  rdx = 0x00000000632e6e72
rdi = 0x0000602000004890  rsi = 0x0000000000000000  rbp = 0x00007fff5e63d4b0  rsp = 0x00007fff5e63d4b0
 r8 = 0x0000000000000009   r9 = 0x0000200000000000  r10 = 0x0000000000000000  r11 = 0xffffffffffffffff
r12 = 0x0000000000000000  r13 = 0x0000000000000000  r14 = 0x0000000000000000  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (42sh:x86_64+0x10000329d) in ft_strncmp
==80521==ABORTING

**Comment by alexandre-roulin** [comment]
Fix !
