### ISSUE TITLE
NORME - too much lines in function

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#26]
Error (line 5): function op_pipeline has 26 lines
Error (line 71): function do_heredoc has 33 lines
Error (line 43): function handler_sigchld has 27 lines
Error (line 82): function escape has 29 lines
Error (line 19): function populating has 30 lines
Error (line 39): function key_print_ has 27 lines

**Comment by alexandre-roulin** [comment]
Mine a close @jle-quel A toi de jouer !

**Comment by jle-quel** [comment]
pipeline done
heredoc done
handler done
escape done
populating done
keyprint done
