### ISSUE TITLE
SETENV && UNSETENV && ENV

### ISSUE THREAD

**Issue by jle-quel** [Krystalz42/42sh#32]
The default format to setenv a variable is `variable=value` but I can bypass it: 
`setenv '=test' || 'setenv =========test============test || setenv ======`
Now i can't remove the variable because it doesn't have a name.
`echo $= || echo $test` will not work

**Comment by jle-quel** [comment]
C'est etrange quand on lance un input.sh avec un setenv dedans il me fait un :
input.sh: line 1: setenv: command not found
si je le fais sans le input.sh ca fonctionne bien.

**Comment by razorbarbeuk** [comment]
Ouais je change dans le input il me fait la meme chose... et bash pariel il me fait la meme erreur donc je considere que ca vient du sh

**Comment by jle-quel** [comment]
Due to the special grammar for unsetenv, unsetenv of the variable "_"  cannot me made
