### ISSUE TITLE
ENV

### ISSUE THREAD

**Issue by jle-quel** [Krystalz42/42sh#42]
Variable PATH is full of `(/b/b/b///b/b/b/b/b/b/b/b/b/b/b/b/b/` * 100)`
Cmd: `/bin/ls`
Result: `42sh: command not found: /bin/ls`

Cmd: `setenv PATH="$PATH":/bin/`
Result: `42sh: command not found: /bin//ls` !Everything should be fine here!

**Comment by alexandre-roulin** [comment]
C'EST PAS MA FOT
