### ISSUE TITLE
SEGV 

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#46]
`gbourson √ ping google.com &
[1] 28858
gbourson √ PING google.com (216.58.209.238): 56 data bytes
64 bytes from 216.58.209.238: icmp_seq=0 ttl=55 time=1.407 ms
64 bytes from 216.58.209.238: icmp_seq=1 ttl=55 time=1.358 ms
64 bytes from 216.58.209.238: icmp_seq=2 ttl=55 time=1.294 ms
64 bytes from 216.58.209.238: icmp_seq=3 ttl=55 time=1.414 ms
64 bytes from 216.58.209.238: icmp_seq=4 ttl=55 time=1.342 ms
gbourson √ fg
[1]           Running ping google.com
64 bytes from 216.58.209.238: icmp_seq=5 ttl=55 time=1.275 ms
64 bytes from 216.58.209.238: icmp_seq=6 ttl=55 time=1.302 ms
64 bytes from 216.58.209.238: icmp_seq=7 ttl=55 time=1.326 ms
bg
64 bytes from 216.58.209.238: icmp_seq=8 ttl=55 time=1.348 ms
64 bytes from 216.58.209.238: icmp_seq=9 ttl=55 time=1.380 ms
c^C
--- google.com ping statistics ---
10 packets transmitted, 10 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.275/1.345/1.414/0.044 ms
gbourson √ ASAN:DEADLYSIGNAL
=================================================================
==27323==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010cbfa0ba bp 0x7fff5301d290 sp 0x7fff5301d180 T0)
==27323==The signal is caused by a READ memory access.
==27323==Hint: address points to the zero page.
    #0 0x10cbfa0b9 in move_vertical move_vertical.c:38
    #1 0x10cbefae9 in key_arrow_up key_arrow.c:66
    #2 0x10cbe39a2 in inline_other (42sh:x86_64+0x1000019a2)
    #3 0x10cbe34fd in read_stdin (42sh:x86_64+0x1000014fd)
    #4 0x10cbe2d2f in shell shell.c:28
    #5 0x10cbe2ad3 in main main.c:23
    #6 0x7fffcf6d5234 in start (libdyld.dylib:x86_64+0x5234)

==27323==Register values:
rax = 0x0000000000000000  rbx = 0x00007fff5301d3e0  rcx = 0x0000606000012f28  rdx = 0x0000000000000000
rdi = 0x00007fff5301d3c0  rsi = 0x0000100000000000  rbp = 0x00007fff5301d290  rsp = 0x00007fff5301d180
 r8 = 0x0000000000000009   r9 = 0x0000200000000000  r10 = 0x0000000000000000  r11 = 0xffffffffffffffff
r12 = 0x0000000000000000  r13 = 0x0000000000000000  r14 = 0x0000000000000000  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV move_vertical.c:38 in move_vertical
==27323==ABORTING
[1]    27323 abort      ./42sh`

**Comment by jle-quel** [comment]
Plus gros encore jacquee
