### ISSUE TITLE
Background - WHY ? 

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#48]
Je ne sais pourkoi sanitize pete a cet endroit, j'ai eu ca plusieurs fois

42sh [master]  ✗ ls -lR / >> fildes 2>& err >& top | grep tutu &
[1] 10228 10229
42sh:  Bad file descriptor
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)
==10139==AddressSanitizer CHECK failed: /BuildRoot/Library/Caches/com.apple.xbs/Sources/clang_compiler_rt/clang-900.0.38/src/projects/compiler-rt/lib/sanitizer_common/sanitizer_mac.cc:354 "((owner_)) != (((uptr)pthread_self()))" (0x7fffccf693c0, 0x7fffccf693c0)

**Comment by jle-quel** [comment]
Seulement quand la commande entiere est lancer en bg

**Comment by jle-quel** [comment]
La commande meme si elle est fausse et ne sera pas executer sera quand meme garder dans jobs a cause du pipe

**Comment by jle-quel** [comment]
Par contre pour le saintiwze qui pete, c'est lui meme qui n'arrive pas a se build, todos esta bene

**Comment by alexandre-roulin** [comment]
Fix !
