### ISSUE TITLE
Alias bug

### ISSUE THREAD

**Issue by alexandre-roulin** [Krystalz42/42sh#78]
`aroulin ❯ alias`
`0:l=ls -lG`
`aroulin ❯ git pull`
`git: 'pulls' is not a git command. See 'git --help'.`
`The most similar command is`
`	pull`
`aroulin  ❯`

git pull provoke alias \"0:l=ls -lG\"  and change it in "git pulls -lR "

**Comment by jle-quel** [comment]
Fix
