### ISSUE TITLE
leaks Heredoc files

### ISSUE THREAD

**Issue by razorbarbeuk** [Krystalz42/42sh#8]
Leak: 0x7feef3402b60  size=16  zone: DefaultMallocZone_0x105214000  length: 10  "1510591688"
Leak: 0x7feef3402bd0  size=16  zone: DefaultMallocZone_0x105214000  length: 15  "/tmp/1510591688"
Leak: 0x7feef3402d90  size=16  zone: DefaultMallocZone_0x105214000  length: 15  "/tmp/1510591655"
Leak: 0x7feef3402e70  size=16  zone: DefaultMallocZone_0x105214000  length: 10  "1510591655"
Leak: 0x7feef3700f40  size=16  zone: DefaultMallocZone_0x105214000  length: 10  "1510591667"
Leak: 0x7feef3700f50  size=16  zone: DefaultMallocZone_0x105214000  length: 15  "/tmp/1510591667"

**Comment by alexandre-roulin** [comment]
Done
